name: Build next.js web applications
on: push
jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: install npm dependencies
      run: npm install
    - name: Build project assests
      run: npm run build